export const Skills = [
    { name: "C", image: "/images/C.png" },
    { name: "Java", image: "/images/java.png" },
    { name: "Python", image: "/images/python.png" },
    { name: "JavaScript", image: "/images/javascript.png" },
    { name: "HTML5", image: "/images/html.png" },
    { name: "CSS3", image: "/images/css.png" },
    { name: "Tailwind CSS", image: "/images/tailwind.png" },
    { name: "React.js", image: "/images/react.png" },
    { name: "Redux", image: "/images/redux.png" },
    { name: "Next.js", image: "/images/Next.js.jpeg" },
    { name: "Node.js", image: "/images/nodejs.png" },
    { name: "Express.js", image: "/images/express.png" },
    { name: "Socket.IO", image: "/images/socket.png" },
    { name: "Microservices", image: "/images/microservices.png" },
    { name: "MongoDB", image: "/images/mongo-db.png" },
    { name: "PostgreSQL", image: "/images/postgresql.png" },
    { name: "Redis", image: "/images/redis.png" },
    { name: "Git", image: "/images/git.png" },
    { name: "Docker", image: "/images/docker.png" },
    { name: "AWS", image: "/images/aws.png" },
];

export const Projects = [
    {
        title: "Mindful - AI Health Coach",
        features: [
            "AI-powered journaling & wellness tracking",
            "Mood-based journaling with personalized coaching",
            "Built with Next.js, MongoDB & NextAuth.js",
            "Gemini API for conversational AI guidance",
        ],
        link: ["https://vcode-mindful.vercel.app/", "https://vcode-mindful.vercel.app/"],
        github: "https://github.com/Vaibhu18/Mindful",
        techs: ["⚛️ Next.js", "🛡️ NextAuth.js", "🟢 MongoDB", "🤖 Gemini API"],
        date: "📅 May 28, 2025",
    },
    {
        title: "GenPro - AI Productivity Assistant",
        features: [
            "Generates complete React apps from user prompts",
            "Interactive preview with Sandpack",
            "Built with MERN + Next.js 15",
            "Seamless authentication using Auth.js",
        ],
        link: ["https://vcode-genpro.vercel.app/", "https://vcode-genpro.vercel.app/"],
        github: "https://github.com/Vaibhu18/ThinkAI",
        techs: ["⚛️ MERN with Next.js 15", "🧩 SandPack", "🔐 Auth.js", "🤖 Gemini API"],
        date: "📅 May 22, 2025",
    },
    {
        title: "ThinkAI – AI-Powered Search Platform",
        features: [
            "Context-aware intelligent search responses",
            "Built with MERN + Next.js 15",
            "Clean, responsive UI with Tailwind",
            "Authentication powered by Clerk",
        ],
        link: ["/images/thinkai.png", "https://vcode-thinkai.vercel.app/"],
        github: "https://github.com/Vaibhu18/ThinkAI",
        techs: ["⚛️ MERN with Next.js 15", "🎨 Tailwind CSS", "🔐 Clerk", "🤖 Gemini API"],
        date: "📅 May 11, 2025",
    },
    { title: "🏫 Top Coders Academy", features: ["Mock learning platform with payments", "Razorpay SDK for secure transactions", "Built with Next.js Fullstack + Tailwind", "Certificates generated instantly"], link: ["https:tca-vcode.vercel.app/", "https:tca-vcode.vercel.app/"], github: "https:github.com/Vaibhu18/TCA-Cirtificates", techs: ["⚛️ Next.js 15", "🎨 Tailwind CSS", "🗃️ MongoDB", "🔐 NextAuth.js", "💳 Razorpay SDK", "🧪 Zod"], date: "📅 Jan 14, 2025", },
    { title: "🌐 Personal Portfolio – Developer Showcase", features: ["Modern and responsive developer portfolio", "Showcases skills, projects & background", "Built with Next.js, React & Tailwind", "Clean design, optimized for all devices"], link: ["https:vcode-portfolio.vercel.app", "https:vcode-portfolio.vercel.app"], github: "https:github.com/Vaibhu18/Portfolio-2.O", techs: ["🧱 HTML", "🎨 CSS", "📜 JavaScript", "⚛️ React.js"], date: "📅 Jan 13, 2025", },
];

export const PullRequests = [
    {
        request: "feat: enhance team form validation and error handling",
        skills: ["Frontend", "React"],
        organization: "Voxora Cloud",
        status: "Merged",
        date: "Aug 2025",
        action: "https://github.com/voxora-cloud/voxora/pull/20",
    },
    {
        request: "feat: add contrast color utility for team color display in agent details",
        skills: ["Frontend", "React"],
        organization: "Voxora Cloud",
        status: "Merged",
        date: "Aug 2025",
        action: "https://github.com/voxora-cloud/voxora/pull/21",
    },
    // {
    //     request: "feat: add contrast color utility for team color display in agent details",
    //     skills: ["Frontend", "React"],
    //     organization: "Voxora Cloud",
    //     status: "Merged",
    //     date: "Aug 2025",
    //     action: "https://github.com/voxora-cloud/voxora/pull/21",
    // },
    // {
    //     request: "feat: add contrast color utility for team color display in agent details",
    //     skills: ["Frontend", "React"],
    //     organization: "Voxora Cloud",
    //     status: "Merged",
    //     date: "Aug 2025",
    //     action: "https://github.com/voxora-cloud/voxora/pull/21",
    // },
    // {
    //     request: "feat: add contrast color utility for team color display in agent details",
    //     skills: ["Frontend", "React"],
    //     organization: "Voxora Cloud",
    //     status: "Merged",
    //     date: "Aug 2025",
    //     action: "https://github.com/voxora-cloud/voxora/pull/21",
    // },
    // {
    //     request: "feat: add contrast color utility for team color display in agent details",
    //     skills: ["Frontend", "React"],
    //     organization: "Voxora Cloud",
    //     status: "Merged",
    //     date: "Aug 2025",
    //     action: "https://github.com/voxora-cloud/voxora/pull/21",
    // }
];

